services:
  - type: web
    name: portfolio-kablankan
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://portfolio-kablankan.onrender.com
